---
title: "Assignment 4"
author: "Getrude Gichuhi"
date: '2022-06-10'
output: pdf_document
---

```{r}
#install.packages('npreg')
#install.packages('gam')
#install.packages('ISLR')
```




```{r setup, include=FALSE}
library(splines)
library(npreg)
library(ISLR)
library(dplyr)
library(ggplot2)
library(gam)
```



```{r cars}
summary(Wage)

dataset = Wage
```
## Regression Splines 

```{r}
lm_mod = lm(wage ~ year + age, data = Wage)
summary(lm_mod)
```

```{r}
plot(Wage$age, Wage$wage)
```

Generate a sequence of age values spanning the range

```{r}
agelims = Wage %>%
  select(age)%>%
  range
```

Get the min/max values of age using the range () function

```{r}
grid1 = seq(from =min(agelims), to =max(agelims))
```


Fitting a regression spline using basic functions 

```{r}
fit = lm(wage~bs(age, df=6), data = Wage)
summary(fit)
```

```{r}
pred = predict(fit, newdata = list(age = grid1), se = TRUE)

summary(pred)
```

Compute error bands (2*SE)

```{r}
se_bands = with(pred, cbind("upper" = fit+2*se.fit,
                            "lower" = fit-2*se.fit))
```

Plot the Spline and the error bands

```{r}
ggplot() +
  geom_point(data = Wage, aes(x = age, y = wage)) +
  geom_line(aes(x = grid1, y = pred$fit), color = "#0000FF") + 
  geom_ribbon(aes(x = grid1, 
                  ymin = se_bands[,"lower"], 
                  ymax = se_bands[,"upper"]), 
              alpha = 0.3) +
  xlim(agelims)
```


## Smooth Splines

Fit smooth splines 

```{r}
fit2 = with(Wage, smooth.spline(age, wage, df =20))
fit2_cv = with(Wage, smooth.spline(age, wage, cv = TRUE))

summary(fit2)
summary(fit2_cv)

```

Plot the smoothing splines 

```{r}
ggplot() +
  geom_point(data = Wage, aes(x = age, y = wage)) +
  geom_line(aes(x = fit2$x, y = fit2$y, 
                color = "16 degrees of freedom"))  +
  geom_line(aes(x = fit2_cv$x, y = fit2_cv$y, 
                color = "6.8 effective degrees of freedom")) +
  theme(legend.position = 'bottom')+ 
  labs(title = "Smoothing Splines", colour="")

```

## GAMs

```{r}
gam1 = lm(wage~ns(year, 4) + ns(age, 5) + education, data = Wage)
summary(gam1)
```

```{r}
gam2 = gam(wage~s(year, 4) + s(age, 5) + education, data = Wage)
par(mfrow = c(1,3))
plot(gam2, se = TRUE, col = "blue")
```

```{r}
par(mfrow = c(1,3))
plot(gam1, se = TRUE, col = "red")
```

``` {r}
gam_lm_year= gam(wage ~ year + s(age, 5) + education, data = Wage)
print(anova(gam_lm_year, gam2, test = "F"))
summary(gam2)
```

```{r}
preds = predict(gam_lm_year, newdata = Wage)
summary(preds)
```

## Logistic Regression GAMS

```{r}
gam_log = gam(I(wage>250) ~ year + s(age, df = 6) + education,
              family = binomial, data = Wage)
par(mfrow=c(1,3))
plot(gam_log, se = TRUE, col = "purple")
```

```{r}
with(Wage, table(education, I(wage>250)))
```

```{r}
College_ed=Wage %>%
  filter(education !="1. <HS Grad")

gam_log2 = gam(I(wage>250) ~ year + s(age, df = 6) +education, 
               family = binomial, data = College_ed)

par(mfrow=c(1,3))

plot(gam_log2, se = TRUE, col = "Red")
```






